/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'numTravelers' : IDL.Nat,
  'travelDates' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
  'budgetRange' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'numTravelers' : IDL.Nat,
    'travelDates' : IDL.Opt(IDL.Text),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
    'budgetRange' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };